### ISSUE TITLE
Use one component as dynamic component

### ISSUE THREAD

**Issue by Debanjan123** [giscafer/primeng-ext#1]
i am using one component for two tabs.Now i have two diff data sets that i want to use for two diff tabs..
But 2nd data set reflecting in both tabs.....
i want 1st data set has to bind 1st tab,and 2nd should bind on 2nd tab /...

**Comment by giscafer** [comment]
use the instance.data1 for 1st data set，instance.data2 for 2nd data set。

solution two:
you should define a variable to distinguish between 1nd and 2nd tab，Hypothesis is A，define a object to store data set，Hypothesis is B，then B[''+A]=data set，

**Comment by Debanjan123** [comment]
Hi giscafer, thank u for ur reply...
but i don't get ur answer.
this is my code ....

    loadComponent() {
        if (!this.tabItem.component) {
            return false;
        }
        const componentFactory = this.componentFactoryResolver.resolveComponentFactory(this.tabItem.component);
        this.dynamicContentContainer.clear();
        this.componentRef = this.dynamicContentContainer.createComponent(componentFactory);
        if (this.componentRef.instance.output) {
            this.componentRef.instance.output.subscribe((event) => {
                alert(event);
            });
        }
           **(<TabConfig>this.componentRef.instance).data = this.data;**
    }
Now see there are two tabs where i have loaded same component two times and this.data is actually dataset,which is instantiated within dynamically created component..
Now this.data is two diff dataset which is suppose to be diff within different tabs..but it is reflecting same dataset on both tabs..
for example : (<TabConfig>this.componentRef.instance).data  ='github' --> for 1st tab
(<TabConfig>this.componentRef.instance).data ='bitbucket' --> for 2nd tab 
but in both component it is reflecting 'bitbucket'

**Comment by giscafer** [comment]
sorry,forgive my poor english

> for example : (this.componentRef.instance).data ='github' --> for 1st tab
> (this.componentRef.instance).data ='bitbucket' --> for 2nd tab
> but in both component it is reflecting 'bitbucket'

i guess in your code ,`(this.componentRef.instance).data ` is the same (Object Reference)，you must use two different variables to save the data.

```ts
loadComponent() {
    if (!this.tabItem.component) {
        return false;
    }
    const componentFactory = this.componentFactoryResolver.resolveComponentFactory(this.tabItem.component);
    this.dynamicContentContainer.clear();
    this.componentRef = this.dynamicContentContainer.createComponent(componentFactory);
    if (this.componentRef.instance.output) {
        this.componentRef.instance.output.subscribe((event) => {
            alert(event);
        });
    }
       let tabName=this.tabItem.name;
       **(<TabConfig>this.componentRef.instance).data[tabName] = this.data;**
}

//Then in  the tab compoent you get the data according to the tabName
 ngOnInit() {
   let _data=this.data[tabName];// tabName is current tab own unique name
}
```


## in my code，there is not have this problem

**every tab create a new component instance**

![20180103142937](https://user-images.githubusercontent.com/8676711/34510941-067019c6-f093-11e7-8b1e-8f8aa360602f.png)
![20180103142956](https://user-images.githubusercontent.com/8676711/34510942-06a7086e-f093-11e7-8e96-82546c3aee11.png)
![20180103143412](https://user-images.githubusercontent.com/8676711/34510965-3a1d162a-f093-11e7-9669-9bb8a4a800db.png)
![tim 20180103143425](https://user-images.githubusercontent.com/8676711/34510969-437327a0-f093-11e7-8730-7a4e1fd9bb6b.png)

## tab-panel.ts

```ts
/**
 * Created by giscafer on 2017-07-19.
 */
import {
    Component,
    OnInit,
    Input,
    AfterViewInit,
    ViewChild,
    ComponentFactoryResolver,
    Type,
    ViewContainerRef
} from "@angular/core";
import {TabConfig} from "./TabConfig";


@Component({
    selector: "ui-tab-panel",
    template: "<div #dynamicContainer></div>"
})
export class UITabPanel implements OnInit,AfterViewInit {

    @Input()
    tabItem: TabConfig;

    @ViewChild( "dynamicContainer", { read: ViewContainerRef } ) dynamicContentContainer: ViewContainerRef;

    currentTabIndex: number = 1;

    constructor(private componentFactoryResolver: ComponentFactoryResolver) {
    }

    ngOnInit(): void {
        this.loadComponent();
    }

    ngAfterViewInit(): void {
    }


    loadComponent() {
        // this.currentTabIndex = (this.currentTabIndex + 1) % this.tabs.length;

        let componentFactory = this.componentFactoryResolver.resolveComponentFactory(this.tabItem.component);

        // let viewContainerRef = this.tabHost.viewContainerRef;
        this.dynamicContentContainer.clear();

        let componentRef = this.dynamicContentContainer.createComponent(componentFactory);
        (<TabConfig>componentRef.instance).data = this.tabItem.data;
    }


}

```

**Comment by Debanjan123** [comment]
@giscafer  thank you so much .....i did a small mistake ..now it is working fine
